# Generated by Django 5.2.11 on 2026-02-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kampanya Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='campaigns/', verbose_name='Görsel')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
    ]
