# Generated by Django 5.2.11 on 2026-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Danışan Adı')),
                ('client_email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('date', models.DateField(verbose_name='Randevu Tarihi')),
                ('time', models.CharField(choices=[('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 11:00'), ('11:00', '11:00 - 12:00'), ('13:00', '13:00 - 14:00'), ('14:00', '14:00 - 15:00'), ('15:00', '15:00 - 16:00'), ('16:00', '16:00 - 17:00')], max_length=10, verbose_name='Randevu Saati')),
                ('message', models.TextField(blank=True, verbose_name='Notunuz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'unique_together': {('date', 'time')},
            },
        ),
    ]
