# Generated by Django 5.2.11 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hizmet Başlığı')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('icon', models.CharField(choices=[('fas fa-couch', '🛋️ Terapi Koltuğu (Bireysel)'), ('fas fa-users', '👥 Çift / Grup Terapisi'), ('fas fa-child', '🧸 Çocuk / Ergen Terapisi'), ('fas fa-brain', '🧠 Bilişsel / Beyin'), ('fas fa-heart', '❤️ İlişki / Duygusal'), ('fas fa-comments', '💬 Danışmanlık / Konuşma'), ('fas fa-hand-holding-heart', '🤲 Destek / Yas Süreci'), ('fas fa-puzzle-piece', '🧩 Problem Çözme / Otizm'), ('fas fa-laptop', '💻 Online Terapi'), ('fas fa-user-md', 'doctor Klinik Psikolog'), ('fas fa-balance-scale', '⚖️ İş-Yaşam Dengesi'), ('fas fa-tree', '🌳 Gelişim / Büyüme'), ('fas fa-smile', '😊 Pozitif Psikoloji'), ('fas fa-feather', '🪶 Hafifleme / Stres'), ('fas fa-infinity', '♾️ Farkındalık (Mindfulness)')], default='fas fa-couch', max_length=50, verbose_name='Hizmet İkonu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hizmet / Terapi Türü',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
