# Generated by Django 5.2.11 on 2026-02-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Kampanya', 'verbose_name_plural': 'Kampanyalar'},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hizmet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Bekliyor (Onaylanmadı)'), ('confirmed', '✅ Onaylandı (Randevu Kesinleşti)'), ('completed', '🏁 Tamamlandı'), ('cancelled', '❌ İptal Edildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], max_length=10, verbose_name='Randevu Saati'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='campaigns/%Y/%m/', verbose_name='Kampanya Görseli'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='link',
            field=models.URLField(blank=True, verbose_name='Tıklanınca Gideceği Link'),
        ),
    ]
