# Generated by Django 5.2.11 on 2026-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Blog Başlığı')),
                ('short_description', models.TextField(max_length=300, verbose_name='Kısa Açıklama (Önizleme)')),
                ('content', models.TextField(verbose_name='İçerik (Uzun Yazı)')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Kapak Resmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
