# Generated by Django 5.2.11 on 2026-03-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Danışan Adı Soyadı')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_session_date', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('summary', models.TextField(blank=True, verbose_name='Genel Değerlendirme')),
            ],
            options={
                'verbose_name': 'Danışan',
                'verbose_name_plural': 'Danışanlar',
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(verbose_name='Seans Notu')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='patient_files/', verbose_name='Ek Dosya (Test/PDF)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.patient')),
            ],
            options={
                'verbose_name': 'Seans Notu',
                'verbose_name_plural': 'Seans Notları',
            },
        ),
    ]
