# Generated by Django 5.2.11 on 2026-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_sessionnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Bekliyor'), ('confirmed', '✅ Onaylandı'), ('completed', '🏁 Tamamlandı'), ('cancelled', '❌ İptal Edildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fas fa-couch', '🛋️ Terapi Koltuğu (Bireysel)'), ('fas fa-users', '👥 Çift / Grup Terapisi'), ('fas fa-child', '🧸 Çocuk / Ergen Terapisi'), ('fas fa-brain', '🧠 Bilişsel / Beyin'), ('fas fa-laptop', '💻 Online Terapi')], default='fas fa-couch', max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='patient_files/'),
        ),
    ]
