# Generated by Django 5.2.11 on 2026-03-06 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionnote',
            options={},
        ),
        migrations.RemoveField(
            model_name='sessionnote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sessionnote',
            name='file_attachment',
        ),
        migrations.RemoveField(
            model_name='sessionnote',
            name='patient',
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Danışan Adı'),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
    ]
